import { useState } from "react";
import { Info, Star, Save, Copy, Download, Mail, MessageCircle, Loader2, HardHat } from "lucide-react";
import { useAuth } from "../lib/auth";
import api from "../lib/api";
import { toast } from "sonner";
import { downloadPdf, pdfBlobUrl, generatePdf } from "../lib/pdf";
import { emojiFor } from "../lib/tools-config";
import { TradeSwitcher } from "./TradeSwitcher";

export default function ToolHeader({ tool, infoOpen, setInfoOpen }) {
  const { user, refresh } = useAuth();
  const [tradeSwitchOpen, setTradeSwitchOpen] = useState(false);
  const isFav = (user?.favourites || []).includes(tool.id);

  const toggleFav = async () => {
    const current = user?.favourites || [];
    const next = isFav ? current.filter(x => x !== tool.id) : [...current, tool.id];
    try {
      await api.post("/profile/update", { favourites: next });
      await refresh();
      toast.success(isFav ? "Removed from favourites" : "Added to favourites");
    } catch { toast.error("Could not update favourites"); }
  };

  return (
    <div className="mb-6">
      <div className="flex items-start justify-between gap-4 mb-3 flex-wrap">
        <div>
          <div className="text-[#E8A020] text-xs uppercase tracking-widest mb-2">{tool.section}</div>
          <h1 className="font-display text-4xl md:text-5xl tracking-tight flex items-center gap-3">
            <span className="text-3xl md:text-4xl">{emojiFor(tool.id)}</span>
            <span>{tool.name}</span>
          </h1>
          <button
            onClick={() => setTradeSwitchOpen(true)}
            className="mt-3 inline-flex items-center gap-2 text-xs px-3 py-1.5 rounded-full border border-[#E8A020]/30 hover:border-[#E8A020]/60 hover:bg-[#E8A020]/5 transition-colors"
            data-testid="tool-trade-switch"
          >
            <HardHat size={12} className="text-[#E8A020]" />
            <span className="text-[#A19D94]">Personalised for</span>
            <span className="text-[#F0EDE8] font-semibold">{user?.trade || "Choose trade"}</span>
            <span className="text-[#E8A020] uppercase tracking-widest text-[10px]">Switch</span>
          </button>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={() => setInfoOpen(!infoOpen)} className="btn-secondary flex items-center gap-2" data-testid="tool-info-btn">
            <Info size={16} /> Info
          </button>
          <button onClick={toggleFav} className={`btn-secondary flex items-center gap-2 ${isFav ? "text-[#E8A020] border-[#E8A020]/40" : ""}`} data-testid="tool-fav-btn">
            <Star size={16} fill={isFav ? "#E8A020" : "none"} /> Favourite
          </button>
        </div>
      </div>
      {infoOpen && (
        <div className="card-dark p-4 text-sm text-[#A19D94] mb-4" data-testid="tool-info-panel">{tool.info}</div>
      )}
      <TradeSwitcher open={tradeSwitchOpen} onClose={() => setTradeSwitchOpen(false)} />
    </div>
  );
}

export function ResultActions({ title, content, toolId }) {
  const { user } = useAuth();
  const [busy, setBusy] = useState(null);

  const onSave = async () => {
    setBusy("save");
    try {
      await api.post("/documents/save", { title, toolId, content });
      toast.success("Saved to your history");
    } catch { toast.error("Save failed"); } finally { setBusy(null); }
  };
  const onCopy = async () => {
    try { await navigator.clipboard.writeText(content); toast.success("Copied"); } catch { toast.error("Copy failed"); }
  };
  const onPdf = () => downloadPdf({ title, content, user });
  const onEmail = () => {
    const subject = encodeURIComponent(title || "Document from Morris");
    const body = encodeURIComponent(content);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };
  const onWhatsAppText = () => {
    const text = encodeURIComponent(`${title}\n\n${content}\n\n— Generated by Morris (morrisapp.co.uk)`);
    window.open(`https://wa.me/?text=${text}`, "_blank");
  };
  const onWhatsAppPdf = () => {
    // Download PDF first so user can attach it, then open WhatsApp
    downloadPdf({ title, content, user });
    setTimeout(() => {
      const text = encodeURIComponent(`${title}. please find the PDF attached. (Generated by Morris)`);
      window.open(`https://wa.me/?text=${text}`, "_blank");
    }, 400);
  };

  return (
    <div className="flex flex-wrap gap-2 mt-5" data-testid="result-actions">
      <ActionBtn onClick={onSave} icon={<Save size={14} />} label="Save" busy={busy === "save"} testId="action-save" />
      <ActionBtn onClick={onCopy} icon={<Copy size={14} />} label="Copy" testId="action-copy" />
      <ActionBtn onClick={onPdf} icon={<Download size={14} />} label="Download PDF" testId="action-pdf" />
      <ActionBtn onClick={onEmail} icon={<Mail size={14} />} label="Email" testId="action-email" />
      <ActionBtn onClick={onWhatsAppText} icon={<MessageCircle size={14} />} label="WhatsApp text" testId="action-wa-text" />
      <ActionBtn onClick={onWhatsAppPdf} icon={<MessageCircle size={14} />} label="WhatsApp PDF" testId="action-wa-pdf" />
    </div>
  );
}

function ActionBtn({ onClick, icon, label, busy, testId }) {
  return (
    <button onClick={onClick} className="btn-secondary text-xs flex items-center gap-2" disabled={busy} data-testid={testId}>
      {busy ? <Loader2 size={14} className="animate-spin" /> : icon}
      {label}
    </button>
  );
}
