import { Link } from "react-router-dom";
import { Scale } from "lucide-react";

const SECTIONS = [
  { h: "About Morris", b: "Morris generates documents to assist UK tradespeople and construction firms. Documents generated by Morris are for administrative assistance only and do not constitute legal, tax, health and safety or professional advice." },
  { h: "Your Responsibility", b: "You are solely responsible for reviewing all documents generated by Morris before use. Always verify accuracy and seek professional advice where required." },
  { h: "Limitation of Liability", b: "Morris Construction Tech Ltd accepts no liability for any loss, damage, injury, claim, penalty or other consequence arising from reliance on documents generated by the platform." },
  { h: "Subscriptions", b: "Subscriptions are billed monthly. Cancellation takes effect at the end of the current billing period. No refunds are provided for unused subscription periods." },
  { h: "Governing Law", b: "These terms are governed by the laws of England and Wales. Morris Construction Tech Ltd, ICO Registration C1923529." },
  { h: "Contact", b: "For any questions contact hello@morrisapp.co.uk or visit morrisapp.co.uk." },
];

export default function TermsConditions() {
  return (
    <div className="p-6 md:p-10 max-w-3xl mx-auto" data-testid="page-terms">
      <div className="mb-8">
        <div className="text-[#E8A020] text-xs uppercase tracking-widest mb-2 flex items-center gap-2"><Scale size={14} /> Account</div>
        <h1 className="font-display text-4xl md:text-5xl">Terms and Conditions</h1>
        <div className="h-[2px] w-24 bg-[#E8A020] mt-4" />
      </div>

      <div className="card-dark p-6 md:p-8 space-y-7">
        {SECTIONS.map((s) => (
          <div key={s.h}>
            <h2 className="font-display text-2xl text-[#E8A020] mb-3">{s.h}</h2>
            <p className="text-[#F0EDE8] leading-relaxed text-sm">{s.b}</p>
          </div>
        ))}

        <div className="pt-4 border-t border-[#F0EDE8]/10">
          <Link to="/app" className="text-[#E8A020] text-sm hover:underline">Back to app</Link>
        </div>
      </div>
    </div>
  );
}
