import { jsPDF } from "jspdf";

export function generatePdf({ title, content, user }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  const usable = pageWidth - margin * 2;

  // Branded header bar
  doc.setFillColor(6, 6, 6);
  doc.rect(0, 0, pageWidth, 70, "F");
  // Gold accent strip
  doc.setFillColor(232, 160, 32);
  doc.rect(0, 70, pageWidth, 3, "F");

  // Brand mark "MORRIS"
  doc.setTextColor(232, 160, 32);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("MORRIS", margin, 42);

  // Company / user line
  doc.setTextColor(240, 237, 232);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const company = user?.companyName || user?.fullName || user?.username || "";
  doc.text(company.toUpperCase(), pageWidth - margin, 30, { align: "right" });
  doc.text(`${new Date().toLocaleDateString("en-GB")}`, pageWidth - margin, 44, { align: "right" });

  // Title
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(title || "Document", margin, 110);

  // Body
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(20, 20, 20);

  const lines = doc.splitTextToSize(content || "", usable);
  let y = 135;
  const pageHeight = doc.internal.pageSize.getHeight();
  const bottom = pageHeight - 60;
  const lineHeight = 14;

  lines.forEach((line) => {
    if (y > bottom) {
      addFooter(doc, pageWidth, pageHeight);
      doc.addPage();
      y = 60;
    }
    doc.text(line, margin, y);
    y += lineHeight;
  });
  addFooter(doc, pageWidth, pageHeight);

  return doc;
}

function addFooter(doc, pageWidth, pageHeight) {
  doc.setDrawColor(232, 160, 32);
  doc.setLineWidth(0.5);
  doc.line(48, pageHeight - 46, pageWidth - 48, pageHeight - 46);
  doc.setTextColor(110, 110, 110);
  doc.setFontSize(8);
  doc.text("Generated by Morris  •  morrisapp.co.uk  •  Built by a tradesman. For tradesmen.", 48, pageHeight - 28);
  doc.text("Morris Construction Tech Ltd  •  ICO C1923529", pageWidth - 48, pageHeight - 28, { align: "right" });
}

export function downloadPdf({ title, content, user }) {
  const doc = generatePdf({ title, content, user });
  const safe = (title || "morris-document").toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 60);
  doc.save(`${safe}.pdf`);
}

export function pdfBlobUrl({ title, content, user }) {
  const doc = generatePdf({ title, content, user });
  return doc.output("bloburl");
}
