import { jsPDF } from "jspdf";

export function generatePdf({ title, content, user, photo, photoCaption }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  const usable = pageWidth - margin * 2;

  // Branded header bar
  doc.setFillColor(6, 6, 6);
  doc.rect(0, 0, pageWidth, 70, "F");
  // Gold accent strip
  doc.setFillColor(232, 160, 32);
  doc.rect(0, 70, pageWidth, 3, "F");

  // Brand mark "MORRIS"
  doc.setTextColor(232, 160, 32);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("MORRIS", margin, 42);

  // Company / user line
  doc.setTextColor(240, 237, 232);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const company = user?.companyName || user?.fullName || user?.username || "";
  doc.text(company.toUpperCase(), pageWidth - margin, 30, { align: "right" });
  doc.text(`${new Date().toLocaleDateString("en-GB")}`, pageWidth - margin, 44, { align: "right" });

  // Title
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(title || "Document", margin, 110);

  // Body
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(20, 20, 20);

  const lines = doc.splitTextToSize(content || "", usable);
  let y = 135;
  const pageHeight = doc.internal.pageSize.getHeight();
  const bottom = pageHeight - 60;
  const lineHeight = 14;

  // Detect the line that contains the contractor Signature field so we can
  // stamp the user's saved signature image directly below it.
  const sigLineMatcher = /^Signature:\s/i;
  let sigStampedY = null;

  lines.forEach((line) => {
    if (y > bottom) {
      addFooter(doc, pageWidth, pageHeight);
      doc.addPage();
      y = 60;
    }
    doc.text(line, margin, y);

    // If this is the contractor "Signature:" line AND a signature image is on file,
    // stamp the signature 4pt below the text on the same row.
    if (sigStampedY === null && user?.signature && sigLineMatcher.test(line)) {
      try {
        const sigW = 130;
        const sigH = 46;
        // Place image slightly to the right of "Signature:" label
        doc.addImage(user.signature, "PNG", margin + 60, y - 32, sigW, sigH, undefined, "FAST");
        sigStampedY = y;
      } catch (e) {
        if (process.env.NODE_ENV !== "production") console.error("PDF signature embed failed", e);
      }
    }

    y += lineHeight;
  });

  // Embed the photo at the end of the body so it appears WITH the document.
  // Stays on the current page if there is room, otherwise pushes to a new page.
  if (photo) {
    const imgWidth = usable * 0.7;
    const imgHeight = imgWidth * 0.75; // approximate aspect; jsPDF will respect the data URL's aspect after add
    if (y + imgHeight + 40 > bottom) {
      addFooter(doc, pageWidth, pageHeight);
      doc.addPage();
      y = 80;
    } else {
      y += 20;
    }
    // Photo caption (date / time / description) — single styled line above the image
    if (photoCaption) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(110, 110, 110);
      const captionLines = doc.splitTextToSize(photoCaption, usable);
      captionLines.forEach((cl) => { doc.text(cl, margin, y); y += 11; });
      y += 6;
    }
    try {
      // jsPDF accepts data URLs directly. Inferring type from prefix.
      const format = (photo.startsWith("data:image/png") ? "PNG" : "JPEG");
      doc.addImage(photo, format, margin, y, imgWidth, imgHeight, undefined, "FAST");
      // Gold border around photo
      doc.setDrawColor(232, 160, 32);
      doc.setLineWidth(0.5);
      doc.rect(margin, y, imgWidth, imgHeight);
      y += imgHeight + 10;
    } catch (e) {
      if (process.env.NODE_ENV !== "production") console.error("PDF photo embed failed", e);
    }
  }

  addFooter(doc, pageWidth, pageHeight);

  return doc;
}

function addFooter(doc, pageWidth, pageHeight) {
  doc.setDrawColor(232, 160, 32);
  doc.setLineWidth(0.5);
  doc.line(48, pageHeight - 46, pageWidth - 48, pageHeight - 46);
  doc.setTextColor(110, 110, 110);
  doc.setFontSize(8);
  doc.text("Generated by Morris  •  morrisapp.co.uk  •  Built by a tradesman. For tradesmen.", 48, pageHeight - 28);
  doc.text("Morris Construction Tech Ltd  •  ICO C1923529", pageWidth - 48, pageHeight - 28, { align: "right" });
}

export function downloadPdf({ title, content, user, photo, photoCaption }) {
  const doc = generatePdf({ title, content, user, photo, photoCaption });
  const safe = (title || "morris-document").toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 60);
  doc.save(`${safe}.pdf`);
}

export function pdfBlobUrl({ title, content, user, photo, photoCaption }) {
  const doc = generatePdf({ title, content, user, photo, photoCaption });
  return doc.output("bloburl");
}
